version: '3.8'

services:
  kafka:
    image: bitnami/kafka:3.6
    restart: on-failure
    ports:
      - "9092:9092"
    environment:
      - KAFKA_KRAFT_ENABLED=no 
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.9 
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
   

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=TrabalhoFinal
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    container_name: producer
    depends_on:
      - kafka

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: consumer
    depends_on:
      - kafka

      # Serviço do Spark Master (igual ao anterior)
  spark-master:
    image: bitnami/spark:3
    container_name: spark-master
    ports:
      - "8181:8181"
      - "7077:7077"
    volumes:
      - ./apps:/opt/bitnami/spark/apps
      - ./data:/opt/bitnami/spark/data
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  # Serviço do Spark Worker (igual ao anterior)
  spark-worker:
    image: bitnami/spark:3
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./apps:/opt/bitnami/spark/apps
      - ./data:/opt/bitnami/spark/data
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  # Jupyter Notebook para interagir com o Spark
  jupyter-notebook:
    image: jupyter/pyspark-notebook
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./apps:/home/jovyan/work/apps
      - ./data:/home/jovyan/work/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
      # Adicione os pacotes necessários para a integração Spark-Kafka
      - SPARK_OPTS=--packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0
    depends_on:
      - spark-master