services:
   kafka1:
      image: bitnami/kafka:latest
      container_name: kafka1
      ports:
        - 19090:19090
      environment:
        - KAFKA_ENABLE_KRAFT=yes
        - KAFKA_CFG_BROKER_ID=1
        - KAFKA_CFG_NODE_ID=1
        - KAFKA_KRAFT_CLUSTER_ID=c1efea27-733e-4c6a-94c0-67e69f5adfea
        - KAFKA_CFG_PROCESS_ROLES=broker,controller
        - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
        - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:19090,CONTROLLER://:9094
        - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://:9092,EXTERNAL://localhost:19090
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9094
        - ALLOW_PLAINTEXT_LISTENER=yes
      volumes:
        - kafka1-data:/bitnami/kafka
volumes:
   kafka1-data:
