version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
  volumes:
    - minio_data:/data
  ports:
    - "9000:9000"
    - "9001:9001"       #console UI
  command: server /data --console-address ":9001"

  uploader:
    build: ./uploader
    contaimer_name: uploader
    depends_on:
      - minio
    volumes:
      - ./data:/app/data
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin

volumes:
  minio_data: